version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mydb
    environment:
      MYSQL_DATABASE: petexpress
      MYSQL_ROOT_PASSWORD: teste
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  api:
    build: .
    container_name: myapi
    environment:
      DATABASE: petexpress
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: teste
      PORT: 5000
      JWT_SECRET: 'dfgljmdfgijodfgijdfgijo'
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    entrypoint: ["sh", "-c", "sleep 20 && npx sequelize db:migrate && npm start"]

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
