version: '3.8'

services:
  app:
    build: .
    container_name: my-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE=petexpress
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npm run migrate && npm start"]


  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
